export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_FRIENDS_PENDING = 'REQUEST_FRIENDS_PENDING';
export const REQUEST_FRIENDS_SUCCESS = 'REQUEST_FRIENDS_SUCCESS';
export const REQUEST_FRIENDS_FAILED = 'REQUEST_FRIENDS_FAILED';

